### ISSUE TITLE
Hinzufügen eines click overlays für Karte

### ISSUE THREAD

**Issue by frommMoritz** [demostat/demostat#28]
Wenn über die Seite, sowohl Mobil als auch Großer Screen, gescrollt wir wird die Karte automatisch fokussiert und entsprechend auf dieser gezoomt.
In diesem Fall könnte ein kleines overlay welches vor der Karte liegt und erst bei dem 1. Klick verschwindet unerwünschte Interaktionen blockieren. 

Könnte irgendwie so aussehen (alles untested):
```javascript
$('.clickoverlay').on('click', function () {
    $(this).remove();
});
```

der entsprechende Style dazu:
```css
.clickoverlay  {
    z-index: 9999999 !important;
    width: 101%;
    height: 101%;
    color: rgba(0, 0, 0, 0);
    background-color: rgba(0, 0, 0, 0);

    /* https://stackoverflow.com/a/5703632 */
    position: relative;
    top: 50%;
    transform: translateY(-50%); 
}

.clickoverlay:hover {
    color: white;
    background-color: rgba(0, 0, 0, 0.5);
}

```
